name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events for develop and v4 branche.
on:
  push

permissions:
  contents: write

concurrency:
  group: bootloader
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        bits: [32, 64]
        exclude:
          - os: macos-latest
            bits: 32
      # max-parallel: 1
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install Gcc
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install gcc-multilib libghc-zlib-dev zlib1g-dev lib32z1 lib32z1-dev
      - name: Build Bootloader
        run: python waf all --target-arch ${{ matrix.bits }}bit
        working-directory: ./bootloader

      - name: Report issues
        if: failure()
        run: cat bootloader/build/config.log
      
      - name: Copy edited files to a temp dir
        shell: bash
        run: |
          mkdir temp
          for file in $(git ls-files --other --exclude-standard); do
            mkdir -p $(dirname $file)
            cp $file temp/$(dirname $file)
          done
      - name: Upload Bootloader
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.bits }}bit
          path: temp/
  
  commit-changes:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Bootloader
        uses: actions/download-artifact@v3
        with:
          path: temp
      - name: debug
        run: |
          ls -la temp
          find temp
      - name: Move files
        run: mv -f temp/*/* Pyinstaller