name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events for develop and v4 branche.
on:
  push

permissions:
  contents: write

concurrency:
  group: bootloader
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        bits: [32, 64]
        exclude:
          - os: macos-latest
            bits: 32
      max-parallel: 1
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Build Bootloader
        run: python waf all --target-arch ${{ matrix.bits }}bit
        working-directory: ./bootloader
      
      - name: Upload Bootloader
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Update Bootloader"
          branch: ${{ github.ref_name }}